---
title: "APM466 A1"
author: "Zihan Wang"
date: "2/3/2022"
output: html_document
---
```{r}
library(jrvFinance)
```


```{r}
setwd("/Users/derrick/Desktop/UT_course/APM466/A1")
Clean<- read.csv(file="Clean.csv", header=TRUE, sep=",", na = ".")
Dirty <- read.csv(file="Dirty.csv", header=TRUE, sep=",", na = ".")
Clean<- Clean[,-1]
Dirty <- Dirty[,-1]
```

Choose 11 selected bonds.
```{r}
Clean11 <- Clean[c(3,4,5,6,9,14,26,27,29,30,32),]
Dirty11 <- Dirty[c(3,4,5,6,9,14,26,27,29,30,32),]
```

Calculate YTM by Clean Price:
```{r}
attach(Clean11)
### Sort by Time to Maturity
Clean11 <- Clean11[order(month_to_maturity),]
Dates = c("2022/01/10", "2022/01/11","2022/01/12","2022/01/13","2022/01/14","2022/01/17","2022/01/18","2022/01/19","2022/01/20","2022/01/21","2022/01/24")
ytms = matrix(0,11,11)
for (i in c(1:11))  # ith bond
{
  for (j in c(1:11)){   # jth Dates
    ## calculate ytm by bond.yield
    ytm = bond.yield(Dates[j],Clean11$maturity.date[i],coupon=Clean11$coupon[i],freq =2,price = Clean11[i,6+j],comp.freq = 2)
    ytms[i,j] = ytm
    }}
```

```{r}
temp = c("YTM 2022/01/10", "YTM 2022/01/11","YTM 2022/01/12","YTM 2022/01/13","YTM 2022/01/14","YTM 2022/01/17","YTM 2022/01/18","YTM 2022/01/19","YTM 2022/01/20","YTM 2022/01/21","YTM 2022/01/24")
colnames(ytms) <- temp
```

```{r}
approx_ytms <- matrix(0,10,11)
for (i in 1:11){   # ith dates
### interpolation technique to approximate YTMs of (6,12,18,24,30,36,42,48,54,60)
    approx_ytms[,i]=approx(Clean11$month_to_maturity,ytms[,i],xout = seq(6,60,6))$y
  }
```

```{r}
temp = c("YTM 2022/01/10", "YTM 2022/01/11","YTM 2022/01/12","YTM 2022/01/13","YTM 2022/01/14","YTM 2022/01/17","YTM 2022/01/18","YTM 2022/01/19","YTM 2022/01/20","YTM 2022/01/21","YTM 2022/01/24")
# rename the columns of table
colnames(approx_ytms) <- temp
temp = c("6 month","12 month","18 month","24 month","30 month","36 month","42 month","48 month","54 month","60 month")
# rename the rows of table
rownames(approx_ytms) <- temp
```


```{r}
#plot with a 5-year yield curve
approx_ytms = as.data.frame(approx_ytms)
x = c(6,12,18,24,30,36,42,48,54,60)
dev.new(width=10, height=6)
plot(x,approx_ytms$`YTM 2022/01/10`, type="l", col="green", lwd=1, xlab="months" ,ylab="YTM",ylim=c(0.006,0.02))
lines(x, approx_ytms$`YTM 2022/01/11`, col="red", lwd=2)
lines(x, approx_ytms$`YTM 2022/01/12`, col="blue", lwd=2)
lines(x, approx_ytms$`YTM 2022/01/13`, col="yellow", lwd=2)
lines(x, approx_ytms$`YTM 2022/01/14`, col="pink", lwd=2)
lines(x, approx_ytms$`YTM 2022/01/17`, col="grey", lwd=2)
lines(x, approx_ytms$`YTM 2022/01/18`, col="cyan", lwd=2)
lines(x, approx_ytms$`YTM 2022/01/19`, col="black", lwd=2)
lines(x, approx_ytms$`YTM 2022/01/20`, col="orange", lwd=2)
lines(x, approx_ytms$`YTM 2022/01/21`, col="darkred", lwd=2)
lines(x, approx_ytms$`YTM 2022/01/24`, col="royalblue", lwd=2)
legend(50,0.015,legend = Dates, col=c("green","red","blue","yellow","pink","grey","cyan","black","orange","darkred","royalblue"),lty=1:2, cex=0.8)
```

Calculate Spot:
```{r}
attach(Dirty11)
### Sort by Time to Maturity
Dirty11 <- Dirty11[order(month_to_maturity),]
```


```{r}
spots = matrix(0,11,11)
for (i in c(1:11)){
  P = Dirty11[1,7+i]  ## Price of the bond with the earliest maturity date
  FV = 100 + Dirty11$coupon[1] * 100 / 2   ## Future payment at maturity date
  ttm = Dirty11$month_to_maturity[1] / 12  ## t with unit year
  spot = (-log(P/FV))/ttm  ## r = (-ln(P/FV))/T
  spots[1,i] = spot  ## store value in matrix
}
```

```{r}
for (i in c(2:11)){   # ith bond
  for(j in c(1:11)){  # jth date
    P = Dirty11[i,7+j]  ## Price of the bond with the earlist maturity date
    coupon = Dirty11$coupon[i] * 100 / 2  ## coupon payment
    ttm = Dirty11$month_to_maturity[i]/12  ## t with unit year
    ### store time to each coupon payments except the last one.
    coupon_times = seq((6-Dirty11$month_since_last_coupon[i])/12,(Dirty11$month_to_maturity[i]-1)/12,0.5)
    ## Deduce Price by present values of coupon payments
    rest_P = P
    for (m in c(1:length(coupon_times))){
      PV_coupon =coupon * exp(-(spots[m,j]*coupon_times[m]))  # Present value of the coupons
      rest_P = rest_P - PV_coupon
    }
    FV = 100 + coupon  ## Future payment at the maturity date
    spot = (-log(rest_P/FV))/ttm  ## r = (-ln(reest_P/FV))/T
    spots[i,j] = spot
  }
}
```

```{r}
temp = c("Spot 2022/01/10", "Spot 2022/01/11","Spot 2022/01/12","Spot 2022/01/13","Spot 2022/01/14","Spot 2022/01/17","Spot 2022/01/18","Spot 2022/01/19","Spot 2022/01/20","Spot 2022/01/21","Spot 2022/01/24")
## rename columns
colnames(spots) <- temp

```

```{r}
## Rename columns and rows
temp = c("Spot 2022/01/10", "Spot 2022/01/11","Spot 2022/01/12","Spot 2022/01/13","Spot 2022/01/14","Spot 2022/01/17","Spot 2022/01/18","Spot 2022/01/19","Spot 2022/01/20","Spot 2022/01/21","Spot 2022/01/24")
colnames(spots) <- temp
temp = c(Dirty11$month_to_maturity)
rownames(spots) <- temp
```




```{r}
# Plot Spots curves
x = c(Dirty11$month_to_maturity)
spots = as.data.frame(spots)
dev.new(width=10, height=6)
plot(x,spots$`Spot 2022/01/10`, type="l", col="green", lwd=1, xlab="months" ,ylab="spot rate",ylim=c(0.004,0.018))
lines(x, spots$`Spot 2022/01/11`, col="red", lwd=2)
lines(x, spots$`Spot 2022/01/12`, col="blue", lwd=2)
lines(x, spots$`Spot 2022/01/13`, col="yellow", lwd=2)
lines(x, spots$`Spot 2022/01/14`, col="pink", lwd=2)
lines(x, spots$`Spot 2022/01/17`, col="grey", lwd=2)
lines(x, spots$`Spot 2022/01/18`, col="cyan", lwd=2)
lines(x, spots$`Spot 2022/01/19`, col="black", lwd=2)
lines(x, spots$`Spot 2022/01/20`, col="orange", lwd=2)
lines(x, spots$`Spot 2022/01/21`, col="darkred", lwd=2)
lines(x, spots$`Spot 2022/01/24`, col="royalblue", lwd=2)
legend(50,0.013,legend = Dates, col=c("green","red","blue","yellow","pink","grey","cyan","black","orange","darkred","royalblue"),lty=1:2, cex=0.8)
```

```{r}
approx_spots <- matrix(0,10,11)
for (i in 1:11){   # ith dates
  ### interpolation technique to approximate spots of (6,12,18,24,30,36,42,48,54,60)
    approx_spots[,i]=approx(Dirty11$month_to_maturity,spots[,i],xout = seq(6,60,6))$y
  }
```

```{r}
## Rename columns and rows
temp = c("Spot 2022/01/10", "Spot 2022/01/11","Spot 2022/01/12","Spot 2022/01/13","Spot 2022/01/14","Spot 2022/01/17","Spot 2022/01/18","Spot 2022/01/19","Spot 2022/01/20","Spot 2022/01/21","Spot 2022/01/24")
colnames(approx_spots) <- temp
temp = c("6 month","12 month","18 month","24 month","30 month","36 month","42 month","48 month","54 month","60 month")
rownames(approx_spots) <- temp
```


Forward rate:
```{r}
forward = matrix(0,4,11)
for (i in 1:4){
  for (j in 1:11){
    ## Calculate one-year forward rate
    r1 = approx_spots[2,j]  ## continuous 1-year spot rate
    t1 = 1 
    rj = approx_spots[2*(i+1),j] ## continuous i+1 year spot rate
    tj = i + 1
    forward[i,j] = (rj*tj-r1*t1)/(tj-t1) ## f_1j = (rj*tj-r1*1)/(tj-1)
  }
}

```

```{r}
# Rename the columns and rows
temp = c("Forward 2022/01/10", "Forward 2022/01/11","Forward 2022/01/12","Forward 2022/01/13","Forward 2022/01/14","Forward 2022/01/17","Forward 2022/01/18","Forward 2022/01/19","Forward 2022/01/20","Forward 2022/01/21","Forward 2022/01/24")
colnames(forward) <- temp
temp = c("1yr-1yr","1yr-2yr","1yr-3yr","1yr-4yr")
rownames(forward) <- temp

forward = as.data.frame(forward)

```



```{r}
# Plot the forward curve
x = c(1,2,3,4)
dev.new(width=10, height=6)
plot(x,forward$`Forward 2022/01/10`, type="l", col="green", lwd=1, xlab="months" ,ylab="forward rate",ylim = c(0.0135,0.019))
lines(x, forward$`Forward 2022/01/11`, col="red", lwd=2)
lines(x, forward$`Forward 2022/01/12`, col="blue", lwd=2)
lines(x, forward$`Forward 2022/01/13`, col="yellow", lwd=2)
lines(x, forward$`Forward 2022/01/14`, col="pink", lwd=2)
lines(x, forward$`Forward 2022/01/17`, col="grey", lwd=2)
lines(x, forward$`Forward 2022/01/18`, col="cyan", lwd=2)
lines(x, forward$`Forward 2022/01/19`, col="black", lwd=2)
lines(x, forward$`Forward 2022/01/20`, col="orange", lwd=2)
lines(x, forward$`Forward 2022/01/21`, col="darkred", lwd=2)
lines(x, forward$`Forward 2022/01/24`, col="royalblue", lwd=2)
legend(3.4,0.0171,legend = Dates, col=c("green","red","blue","yellow","pink","grey","cyan","black","orange","darkred","royalblue"),lty=1:2, cex=0.8)
```


```{r}
## Plug in the X_ij fomula to calculate log returns of yield
X_yield = matrix(0,5,9)
for (i in 1:5){    ## ith year
  for (j in 1:9){
    r_ij = approx_ytms[2*i,j]
    r_ij1 = approx_ytms[2*i,j + 1]
    x_ij = log(r_ij1/r_ij)
    X_yield[i,j] = x_ij
  }
}
X_yield = as.data.frame(t(X_yield))
colnames(X_yield) <- c("1yr YTM","2yr YTM","3yr YTM","4yr YTM","5yr YTM")
## Covariance matrix of X
cov_yield = cov(X_yield)
cov_yield
```


```{r}
## Plug in the X_ij fomula to calculate log returns of forward rates
X_forward = matrix(0,4,9)
for (i in 1:4){    ## ith year
  for (j in 1:9){
    r_ij = forward[i,j]
    r_ij1 = forward[i,j + 1]
    x_ij = log(r_ij1/r_ij)
    X_forward[i,j] = x_ij
  }
}
X_forward = as.data.frame(t(X_forward))
colnames(X_forward) <- c("1yr-1yr","1yr-2yr","1yr-3yr","1yr-4yr")
## Covariance matrix of X
cov_forward = cov(X_forward)
cov_forward
```



```{r}
## Calculate eigenvalues and eigenvectors respectively
eigen_yield = eigen(cov_yield)
eigen_forward = eigen(cov_forward)
```

```{r}
# Print the eigenvalues and eigenvectors
eigen_yield$values
eigen_yield$vectors
```

```{r}
# Print the eigenvalues and eigenvectors
eigen_forward$values
eigen_forward$vectors
```